image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1776.310713, 0.000000, 748.340681,
          0.000000, 1781.670862, 540.290686,
          0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.055100, 0.042257, -0.000775, 0.000237, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000,
          0.000000, 1.000000, 0.000000,
          0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1760.750000, 0.000000, 748.429387, 0.000000,
          0.000000, 1771.536133, 539.405375, 0.000000,
          0.000000, 0.000000, 1.000000, 0.000000]