/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2000  #1500
    gain: 15.5 #15.5

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    # test_gimbal_v: 0.5

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 65
    

    light.min_ratio: 0.09
    light.max_ratio: 0.5
    light.min_fill_ratio: 0.7
    armor.min_light_ratio: 0.8
    armor.max_small_center_distance: 2.8
    armor.min_large_center_distance: 2.8
    armor.max_large_center_distance: 4.5

    bool bullet_debug_: false
    bullet_binary_thres: 180
    bullet_min_area: 10
    bullet_max_area: 500
    bullet_min_ratio: 0.7
    bullet_max_ratio: 1.3

    classifier_threshold: 0.7
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 15.0

    ekf:
      sigma2_q_xyz_max: 2.0
      sigma2_q_xyz_min: 0.5
      sigma2_q_yaw_max: 6.0
      sigma2_q_yaw_min: 3.0
      sigma2_q_r: 45.0

      r_xyz_factor: 6e-4
      r_yaw: 8e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 0.8

      tracking_thres: 5
      lost_time_thres: 1.0

/fire_control:
  ros__parameters:
    large_armor_width: 0.23
    small_armor_width: 0.135
    large_armor_height: 0.127
    small_armor_height: 0.125
    armor_pitch: 15.0
    s_bias: 0.072
    z_bias: 0.0
    k: 0.022  
    gravity: 9.79

    yaw_motor_res_speed_a: 0.1845
    yaw_motor_res_speed_b: 0.0
    tranfer_thresh: 5
    max_tracking_v_yaw_1: 1.1
    max_tracking_v_yaw_2: 6.0
    max_orientation_angle: 40.0
    max_tracking_error: 2.0
    max_out_error: 0.3

    communite_delay: 0.025
    receive_to_fire_delay: 0.012

    current_v: 22.0



/buff_detector:
  ros__parameters:
    detector:
      model: "buff_quantized.xml"
      nms_threshold: 0.05
      conf_threshold: 0.7
      image_size: 640
      bin_threshold: 95.0 # 65.0
      fault_tolerance_ratio: 0.3

/buff_tracker:
  ros__parameters:
    target_frame: odom

    ekf:
      sigma2_q_xyz: 1e-5
      sigma2_q_theta: 2.09 # a_max * w_max
      sigma2_q_r: 0.0

      r_blade: 6e-4
      r_center: 2e-4

    gns:
      min_a: 0.4
      max_a: 1.3
      min_w: 1.5
      max_w: 2.3
      max_iter: 50
      min_step: 1e-10
      obs_max_size: 150
      a_start: 0.9125
      w_start: 1.942
      c_start: 0.0
      min_first_solve_time: 2.0

    ekf_gns:
      sigma2_q_a: 1e-5
      sigma2_q_w: 1e-5
      sigma2_q_c: 1e2
      r_a: 1e-8
      r_w: 1e-8
      r_c: 1e-8

    tracker:
      lost_time_threshold: 2.0
      max_match_theta: 0.4
      max_match_center_xoy: 1.0

      tracking_threshold: 20

      blade_z_ground: 1603.0
      robot_z_ground: 416.0
      distance: 6626.0
      max_distance_diff: 120.0
