image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1859.382552, 0.000000, 722.716128,
          0.000000, 1865.351088, 490.753999,
          0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.055726, 0.122765, -0.012103, 0.010928, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000,
          0.000000, 1.000000, 0.000000,
          0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1857.163574, 0.000000, 732.705801, 0.000000,
          0.000000, 1864.076050, 481.664239, 0.000000,
          0.000000, 0.000000, 1.000000, 0.000000]
